version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
